version: '3'

services:
  app:
    restart: always
    container_name: scout
    build:
      context: .
    volumes:
      - ./scout:/app/scout
    ports:
      - "${PORT:-8000}:8000"
    environment:
      ENV: localdev
      SCOUT_SHOW_NEWSSPLASH: ${SCOUT_SHOW_NEWSSPLASH:-False}
